### ISSUE TITLE
Offer Build Without Google Play Services Dependency

### ISSUE THREAD

**Issue by krt16s** [Glucosio/glucosio-android#122]
Google's proprietary play-services has been added to the dependencies, could you provide a pure floss build flavor or instead use acra for reporting?

**Comment by bkerensa** [comment]
I'll provide response to this request as soon as we can although it may not be till tomorrow.

**Comment by bkerensa** [comment]
We will be adding a gradle build variant and check to our code like Telegram does.

Hopefully this will resolve this issue and we should have it released in 0.8.3.

We will update this bug once that happens but anticipate to release 0.8.3 in about two to three weeks.

We are using Google Play Services for Invite API and will eventually use it Google Drive backups (opt-in) and do not know of any way to achieve both of these without Google Play Services.

**Comment by bkerensa** [comment]
@PaoloRotolo lets prioritize the build flavor/build variant like we discussed so they can easily build one without GP when they do their builds.

**Comment by bkerensa** [comment]
@krt16s We have looked at a way to do this and there is not any practical way we can see of doing this at this time. One of the main features our users have asked for and diabetics we have done surveying of is the ability to backup to Google Drive and this will be one of many backup options we offer in order to offer this though we do have to have Google Play Services.

We have looked at trying to do a separate build but not found a straightforward way that would not add a significant amount of work for our team. If someone would like to maintain a repo in our organization that is GPS free we would be happy to open that repo and add that person to our organization.

Also if you or anyone else has suggestions on how to offer a GPS free build without adding significant work for our very small team it would be appreciated.

Until one of the two above occurs marking this P3 (Low Priority) and unsetting a milestone and we do not see a way forward currently but this does not mean we do not want to offer a GPS free build.

**Comment by bkerensa** [comment]
@krt16s Any thoughts on my last comment? If you could show us some examples of how other projects have done seperate builds this would be helpful. Please know that the library we are using is still open source.

I noticed you stop building in F-Droid and some people have just migrated to Google Play Store version. might you consider just putting up the warning and building for now? 

Again if you can help us find a good way of doing a GP-free build we would be happy to do this. We will continue to investigate a good way even if we do not hear back from you.

**Comment by krt16s** [comment]
(just fyi: i am rather busy atm, maybe i can look into this the next week)

**Comment by bkerensa** [comment]
@krt16s no worries if you want email us at hello at glucosio.org and I can loop you in with our Android lead who can explain the various ways he has tried to tackle this and why the approaches dont work. We definately want to get a build you can use because the current build on F-Droid has a bug and also lacks all the new features we have added.

We are actually seeing people uninstall the F-Droid version and install from Google Play and while that is fine for us I know your goal is to keep those people using F-Droid.

**Comment by bkerensa** [comment]
@krt16s Since we agree that the code is non-free but understand to a degree the rationale
of F-Droid would it be acceptable for us to just have this be opt-in? So otherwise it is off in the code by default but the user choices whether they would like to toggle it on?

**Comment by krt16s** [comment]
Yikes... forgot about that one.. again.

On Optin: I don't understand, fdroids buildserver just does not have play-services installed. All apps requiring it fail to build.

On floss gradle flavor: 

1) Add the following lines to `app/build.gradle`s android section:
````
    productFlavors {
        floss {
        }
        gplay {
        }
    }
````

2) Change non-free depdencies from `compile ....` to `gplayCompile ...`

3) Now you can seperate source files: Instead of `src/main/` only, `src/floss` and `src/gplay/` will be used in addition, depending on the used flavor. Depending on where you use play-services in your code, it might be tricky to separate it, but that depends on the code... maybe just implement stubs for pure-floss version...

**Comment by bkerensa** [comment]
We are still evaluating this and have had some side discussion with folks at the FSF on F-Droid's policies while were probably in a position to build a F-Droid flavor at this point we need to evaluate whether we want to offer a stripped down experience in order to comply with F-Droid's policies.

This will require some discussion at next core team meeting.

**Comment by mvdan** [comment]
We really don't have a strange policy here. We simply won't distribute non-free software. Including play-services on your APK, even if it's opt-in usage, makes the app non-free.

**Comment by bkerensa** [comment]
@mvdan Our discussion with the staff at the FSF and others (including lawyers specializing in OSS licensing) came to the conclusion that F-Droid's non-free interpretation sets the bar higher that even the FSF and that using play-services API is fine.

**Comment by mvdan** [comment]
It's not an API you are using - it's a non-free library. And you're distributing the non-free library with the apk. How is that fine by the FSF?

**Comment by bkerensa** [comment]
Play-services library is a wrapper for their API it allows Android apps to interact with Google Services. To remove this functionality would cripple things like support for Android Wear for Social Sharing and more.

VLC, Mozilla and other OSS projects use the same library. Anyways if you have questions about that we'd encourage you to dialogue with the FSF but we disagree with your position based on the discussions we've had so far.

**Comment by bkerensa** [comment]
Looks like end of my comment didn't come through:

That said the question here for us is whether to offer a separate build that strips down features which could upset users seeking parity with the Google Play distributed version of our APK. Also do we want to provide a lower level of support just to be in F-Droid.

This is what we need to address and it's a tough one because we'd basically be shipping a very different app.

**Comment by bkerensa** [comment]
Closing this as this will be addressed in issue #219

**Comment by grote** [comment]
> We are still evaluating this and have had some side discussion with folks at the FSF on F-Droid's  policies while were probably in a position to build a F-Droid flavor at this point we need to evaluate whether we want to offer a stripped down experience in order to comply with F-Droid's policies.

@bkerensa Do you mind sharing who you talked to at FSF and what exactly they have told you? I am asking, because there might be a misunderstanding I can help clearing up. (I am with FSFE myself.)

**Comment by bkerensa** [comment]
No it was a private discussion if they choose to chime in they can but I'm not going to put their name out publicly.

**Comment by grote** [comment]
@bkerensa You might want to be careful then with claiming this to be an official FSF position.

**Comment by mvdan** [comment]
I would be surprised to say the least if the FSF were to say that using play-services was fine.

**Comment by bkerensa** [comment]
I never said it was a position of the FSF I would caution you not to put words in my mouth. I said it's our position based on private discussions we've had.

If F-Droid is interested in discussing this in private we'd be happy to loop them in and have a dialogue about it more formally. I'd actually encourage F-Droid to seek feedback to improve their policies from both the FSF and OSI.

Notably at the end of the day F-Droid calls a lot of OSS apps non-free from Mozilla Firefox to others and that's again why I don't think their policies have much weight in defining what is non-free.

We comply with our licensed produced by the FSF and it defines our software as free.

Please direct further discussions to email, mailing list or forum. A bug tracker is not the appropriate place for discussions.
