### ISSUE TITLE
Distribute through Amazon App Store

### ISSUE THREAD

**Issue by da2x** [Glucosio/glucosio-android#185]
Not that I use it, but plenty of other people do.

**Comment by bkerensa** [comment]
We will look into this more next year because of our reliance on Google Play Services for Crash analytics and under the hood features we would likely have to do a entirely desperate build and maintain superstar code which could take away momentum on our Google Play distribution which would be the largest audience. I believe Amazon has less than 1% of Android devices.

**Comment by ghost** [comment]
This is not a priority for now
