### ISSUE TITLE
GlucoseRanges: Unaccessible 'blue' color value for 'ADA' preffered Range

### ISSUE THREAD

**Issue by ghost** [Glucosio/glucosio-android#363]
Hi, 

I've already noticed that every value smaller than `70` would return `purple` so it won't return in any case`blue` color value for `ADA` preferred range, because conditional for this expects values lower than `70` which is as already reserved.

Here is an interesting part of code: 
```
 if (reading < 70) {
            return "purple";
        } else if (reading > 200) {
            return "red";
        } else if (reading > 70 | reading < 200) {
            // if not check with custom ranges
            switch (preferredRange) {
                case "ADA":
                    if (reading >= 70 & reading <= 180) {
                        return "green";
                    } else if (reading < 70) {
                        return "blue";
                    } else if (reading > 180) {
                        return "orange";
                    }
```

Check this code for `69`, `70` and `71` if that what was said is still not clear.

Cheers!

**Comment by riskysnail** [comment]
The hypo and hyper limits are hard coded and perhaps they should be adjusted. This ticket will relate to changes made in #91

**Comment by riskysnail** [comment]
I'm going to commit a change to use 80 instead of 70 which is recommended for hypounawareness and gives us a buffer between low and hypo in our ranges.

I'm also going to do something similar with UK NICE which has a recommendation of 5-7mmol 4-7mmol when waking/before meals. I'll split the difference between 4 and 5 minimums for each so we use 4.5 instead (81 when converted to mg/dl).
